version: 0.2

phases:
  install:
    commands:
      - echo Installing frontend dependencies...
      - npm install
  build:
    commands:
      - echo Building the frontend...
      - npm run build # Adjust command according to your Nx setup
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Preparing artifacts...
      - cd dist/apps/reviewpal-web # Adjust path according to your Nx setup
artifacts:
  files:
    - '**/*'
  base-directory: 'dist/apps/reviewpal-web' # Adjust path according to your Nx setup
